Admin/Gizmobaba/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Gizmobaba.Models;
using Gizmobaba.Service.Interfaces;
using Gizmobaba.Utility;
using AutoMapper;

namespace Gizmobaba.Controllers
{
    [Authorize]
    public class SettingsController : BaseController<SettingsController>
    {
        // GET: Settings
        private readonly IWalletService _walletService;
        private readonly IPermissionsService _permissionsService;
        private readonly IProductService _productService;
        // GET: CategoryManage

        public SettingsController(IWalletService walletService, IPermissionsService permissionsService, IProductService productService)
        {
            this._walletService = walletService;
            this._permissionsService = permissionsService;
            this._productService = productService;
        }
        public ActionResult Index()
        {

            Mapper.CreateMap<WalletDto, WalletViewModel>();
            WalletDto walletData = _walletService.GetWallet();
            WalletViewModel walletViewModel = Mapper.Map<WalletViewModel>(walletData);


            //WalletViewModel walletViewModel = new WalletViewModel();
            //WalletDto data = _walletService.GetWallet();
            //if (data != null)
            //{
            //    walletViewModel = new WalletViewModel
            //    {
            //        WALLET_ID = data.WALLET_ID,
            //        LINKINGPOSTS = data.LINKINGPOSTS,
            //        MAX_USER_PURCHASE = data.MAX_USER_PURCHASE,
            //        OWN_PURCHASE = data.OWN_PURCHASE,
            //        PURCHASE_CERTAIN_TIME = data.PURCHASE_CERTAIN_TIME,
            //        REFERRING_FRIENDS = data.REFERRING_FRIENDS,
            //        REFFERED_FRIENDS_PURCHASES = data.REFFERED_FRIENDS_PURCHASES,
            //        ROLE_ID = data.ROLE_ID,
            //        SHARINGPOSTS = data.SHARINGPOSTS,
            //        SIGNUP = data.SIGNUP
            //    };
            //}
            return View("AddWallet", walletViewModel);
        }
        [HttpGet]
        public ActionResult LoyaltyPrograms(int id = 0)
        {
            int roleId = id;
            IEnumerable<BonusDto> bonusDto;
            Mapper.CreateMap<BonusDto, BonusView>();
            if (roleId == 0)
                bonusDto = _walletService.GetWalletList();
            else
                bonusDto = _walletService.GetWalletListByRole(roleId);

            IEnumerable<BonusView> bonusData = Mapper.Map<List<BonusView>>(bonusDto);
            BonusTypesViewModel model = new BonusTypesViewModel();
            model.BonusView = bonusData;
            return View(model);
        }
        [HttpPost]
        public ActionResult LoyaltyPrograms(GB_BONUS bonus)
        {
            if (bonus != null)
            {
                if (bonus.ROLE_ID == 0)
                    bonus.ROLE_ID = (int)CustomStatus.UserTypes.Customer;
                _walletService.CreateWallet(bonus);
            }
            return RedirectToAction("LoyaltyPrograms");
        }


        [HttpPost]
        public ActionResult AddWallet(M_GB_WALLET wallet)
        {
            wallet.ROLE_ID = (int)CustomStatus.UserTypes.Customer;
            wallet.CREATEDON = DateTime.Now;
            wallet.STATUS = (int)CustomStatus.Status.Active;
            _walletService.AddWallet(wallet);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddDealerWallet(M_GB_WALLET wallet)
        {
            wallet.ROLE_ID = (int)CustomStatus.UserStatus.Dealer;
            wallet.CREATEDON = DateTime.Now;
            wallet.STATUS = 1;
            _walletService.AddWallet(wallet);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult AddMasterFranchiseWallet(M_GB_WALLET wallet)
        {
            wallet.ROLE_ID = (int)CustomStatus.UserStatus.MasterFranchise;
            wallet.CREATEDON = DateTime.Now;
            wallet.STATUS = 1;
            _walletService.AddWallet(wallet);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddRole(int id = 0)
        {
            FeatureTypeViewModel featureTypeViewModel = new FeatureTypeViewModel();
            if (id <= 0)
            {
                IEnumerable<FeatureTypeDto> getFeatureType = _permissionsService.GetFeatureTypes();
                IEnumerable<FeatureTypeModel> getFeatureTypeList = getFeatureType.Select(featureTypeDto => new FeatureTypeModel
                {
                    FEATURE_TYPE = featureTypeDto.FEATURE_TYPE,
                    FEATURE_TYPE_ID = featureTypeDto.FEATURE_TYPE_ID,
                    STATUS = featureTypeDto.STATUS,
                    ROLE_ID = featureTypeDto.ROLE_ID,
                    ID = featureTypeDto.ID
                }).ToList();
                featureTypeViewModel.FeatureType = getFeatureTypeList;
            }
            else
            {
                M_GB_ROLES roles = _permissionsService.GetRoleDetails(id);
                RolesModel rolesModel = new RolesModel
                {
                    ROLE_ID = roles.ROLE_ID,
                    ROLE_DESC = roles.ROLE_DESC,
                    DESCRIPTION = roles.DESCRIPTION
                };
                IEnumerable<FeatureTypeDto> getFeatureTypes = _permissionsService.GetFeatureTypes();
                IEnumerable<FeatureTypeDto> getFeatureType = _permissionsService.GetFeatureAccessByRoleId(id);
                IEnumerable<FeatureTypeModel> getFeatureTypeList = getFeatureTypes.Select(featureTypeDto => new FeatureTypeModel
                {
                    FEATURE_TYPE = featureTypeDto.FEATURE_TYPE,
                    FEATURE_TYPE_ID = featureTypeDto.FEATURE_TYPE_ID,
                    STATUS = featureTypeDto.STATUS,
                    ROLE_ID = featureTypeDto.ROLE_ID,
                    ID = featureTypeDto.ID,
                }).ToList();
                foreach (FeatureTypeDto item in getFeatureType)
                {
                    if (item.STATUS == 1)
                    {
                        FeatureTypeModel featureTypeModel =
                            getFeatureTypeList.FirstOrDefault(a => a.FEATURE_TYPE_ID == item.FEATURE_TYPE_ID);
                        if (featureTypeModel != null)
                            featureTypeModel.chkBox = 1;
                    }
                }
                featureTypeViewModel.FeatureType = getFeatureTypeList;
                featureTypeViewModel.RolesModel = rolesModel;
            }
            return View(featureTypeViewModel);
        }

        [HttpPost]
        public ActionResult AddRole(FormCollection froCollection)
        {
            int id = 0;
            string sucMessage = "";
            string errorMessage = "";
            try
            {
                if (Request.Form["RolesModel.ROLE_ID"] != null) id = Convert.ToInt32(Request.Form["RolesModel.ROLE_ID"]);
                M_GB_ROLES role = new M_GB_ROLES
                {
                    ROLE_DESC = Request.Form["RolesModel.ROLE_DESC"],
                    DESCRIPTION = Request.Form["RolesModel.DESCRIPTION"],
                    ROLE_ID = id
                };
                if (role.ROLE_ID == 0)
                    sucMessage += "Role Added";
                else
                    sucMessage += "Role Updated";
                int roleId = _permissionsService.AddRole(role);
                if (roleId != 0)
                {
                    IEnumerable<FeatureTypeDto> getFeatureType = _permissionsService.GetFeatureTypes().Where(a => a.STATUS == 2);
                    List<M_GB_FEATURE_ACCESS> featureTypesList = getFeatureType.Select(item => new M_GB_FEATURE_ACCESS
                    {
                        FEATURE_TYPE_ID = item.FEATURE_TYPE_ID,
                        ROLE_ID = roleId,
                        STATUS = 0,
                        CREATED_ON = DateTime.Now
                    }).ToList();
                    int count = 3;
                    // ReSharper disable once UnusedVariable
                    foreach (var key in froCollection.AllKeys)
                    {
                        if (count < froCollection.AllKeys.Length)
                        {
                            string list = Request.Form[froCollection.AllKeys[count]];
                            if (list.Split(',').Count() != 0)
                            {
                                foreach (string featureTypeId in list.Split(','))
                                {
                                    int Id = Convert.ToInt32(featureTypeId);
                                    var mGbFeatureAccess = featureTypesList.FirstOrDefault(x => x.FEATURE_TYPE_ID == Id);
                                    if (mGbFeatureAccess != null)
                                        mGbFeatureAccess.STATUS = 1;
                                }
                            }
                        }
                        count++;
                    }
                    foreach (M_GB_FEATURE_ACCESS featureAccess in featureTypesList)
                    {
                        _permissionsService.AddFeatureAccessToRole(featureAccess);
                    }
                    sucMessage = "succefuly " + sucMessage;
                }
            }
            catch (Exception exception)
            {
                errorMessage = exception.ToString();
            }
            TempData["SuccessMessage"] = sucMessage;
            TempData["ErrorMessage"] = errorMessage;
            return RedirectToAction("Roles");
        }

        public ActionResult Roles()
        {
            Mapper.CreateMap<RolesDto, RolesModel>();
            IEnumerable<RolesDto> rolesModels = _permissionsService.GetAllRoles();
            IEnumerable<RolesModel> roles = Mapper.Map<List<RolesModel>>(rolesModels);
            return View(roles);
        }

Admin/Gizmobaba/Views/Settings/AddRole.cshtml
@model Gizmobaba.Models.FeatureTypeViewModel

@{
    ViewBag.Title = "AddRole";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}
<script type="text/javascript">
    $(document).ready(function () {
       
    });
</script>

<div class="page-title">
    <div class="title_left">
        <h3> List of Roles <i class="fa fa-caret-right"></i> Add/Edit Custom Role</h3><br>
    </div>
</div>

<div class="title_content_top">
    <p>
        This interface enables you to view the available predefined or custom roles, which are used for creating role-based users (i.e. store operators). Role-based users are authorized users of your control panel and can access only those functionalities, which are assigned to their mapped roles. You can also create or modify or delete custom roles. You can view and copy the mapped functionalities of any role, and use the copied functionalities while creating a new role.
    </p>
</div>
<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="mmctrl_box mrgin_gap0 mmctrl_tble_line">
            <div class="mmcaption">List of Roles</div>
        @*<form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left">*@
@using (Html.BeginForm("AddRole", "Settings", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return validateForm();" }))
{
    <br>
    <div class="form-group">
        <label class="control-label col-md-2" for="">Role Name <span class="red">*</span> </label>
        <div class="col-md-9">
            @Html.HiddenFor(model=>model.RolesModel.ROLE_ID)
            @Html.TextBoxFor(model => model.RolesModel.ROLE_DESC, new {@class = "form-control", required = "", placeholder = ""})
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2" for="">Role Description </label>
        <div class="col-md-9">
            @Html.TextBoxFor(model => model.RolesModel.DESCRIPTION, new { @class = "form-control", required = "", placeholder = "" })
        </div>
    </div>
            @*</form>*@
    <hr>
    <br>


    <div class="userroles_addedit_select_holder uash_table">
        <!--<h1><input type="checkbox" id="ckbCheckAll"/> Catalog</h1>

        <div class="col-md-4">
            <p id="checkBoxes">
                <input type="checkbox" class="checkBoxClass" id="Checkbox1"/>
                <input type="checkbox" class="checkBoxClass" id="Checkbox2"/>
                <input type="checkbox" class="checkBoxClass" id="Checkbox3"/>
                <input type="checkbox" class="checkBoxClass" id="Checkbox4"/>
                <input type="checkbox" class="checkBoxClass" id="Checkbox5"/>
            </p>
        </div>-->
        @if (Model != null)
        {
            foreach (var item in Model.FeatureType.Where(a => a.STATUS == 1))
            {
                <table class="table mrgin_gap0">
                    <thead>
                    <tr>
                        <th colspan="2"><input type="checkbox" id="ckbCheck_@(item.FEATURE_TYPE_ID)"> @item.FEATURE_TYPE</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody id="checkBoxes">
                    <tr>
                        <td>
                        
                            @if (item.FEATURE_TYPE_ID != 0)
                            {
                                int id = item.FEATURE_TYPE_ID;
                                int count = 1;
                                foreach (var list in Model.FeatureType.Where(a => a.STATUS == 2 && a.ID == id))
                                {
                                    if (list.chkBox == 0)
                                    {
                                        <div class="col-md-4">
                                            <input type="checkbox" name="@item.FEATURE_TYPE" class="checkBoxClass_@(item.FEATURE_TYPE_ID)" id="Checkbox1" value="@list.FEATURE_TYPE_ID"> @list.FEATURE_TYPE
                                        </div>
                                    }
                                    else if (list.chkBox == 1)
                                    {
                                        <div class="col-md-4">
                                            <input type="checkbox" name="@item.FEATURE_TYPE" class="checkBoxClass_@(item.FEATURE_TYPE_ID)" id="Checkbox1" checked="checked" value="@list.FEATURE_TYPE_ID"> @list.FEATURE_TYPE
                                        </div>
                                    }
                                }
                            }
                
                        </td>
                    </tr>
                    </tbody>
                </table>
            }
        }
        <br>


    </div>
    <div class="clearfix"></div>
    <br>


    <div class="col-md-12 graycolorbg0">
        <div class="pull-right">
            <a href="@Url.Action("Roles", "Settings")"><button type="button" class="btn btn-default">Back</button></a>
            <a href="#"><button type="submit" class="btn btn-dark">Save</button></a>
        </div>
    </div>
}
        </div>
    </div>
</div>
<!-- /page content -->
<br>


<script>
    NProgress.done();
    $(document).ready(function () {

        $("#ckbCheck_3007").click(function () {
            $(".checkBoxClass_3007").prop('checked', $(this).prop('checked'));
        });

        $("#ckbCheck_3008").click(function () {
            $(".checkBoxClass_3008").prop('checked', $(this).prop('checked'));
        });

        $("#ckbCheck_3009").click(function () {
            $(".checkBoxClass_3009").prop('checked', $(this).prop('checked'));
        });

        $("#ckbCheck_3010").click(function () {
            $(".checkBoxClass_3010").prop('checked', $(this).prop('checked'));
        });

        $("#ckbCheck_3011").click(function () {
            $(".checkBoxClass_3011").prop('checked', $(this).prop('checked'));
        });

        $("#ckbCheck_3012").click(function () {
            $(".checkBoxClass_3012").prop('checked', $(this).prop('checked'));
        });
        $("#ckbCheck_3013").click(function () {
            $(".checkBoxClass_3013").prop('checked', $(this).prop('checked'));
        });


        $('button[type="submit"]').click(function () {
            var emptyVal = 0;
            $('[required]').each(function () {
                if ($(this).val() == "") {
                    emptyVal = 1;
                }
            });
            if (emptyVal != 1)
                $('.loader-container').removeClass('hide');
        });
    });
    function validateForm() {
        $('.loader-container').removeClass('hide');
    }
</script>
<div class='loader-container hide'>
    <div class='loader'>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--text'></div>
    </div>
</div>
<link href="~/Content/loader.css" rel="stylesheet" />

Admin/Gizmobaba/Views/Settings/CheckoutOptions.cshtml
@model IEnumerable<Gizmobaba.Models.PaymentModel>
@{
    ViewBag.Title = "CheckoutOptions";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}


    <div class="page-title">
        <div class="title_left">
            <h3>Checkout Options <i class="fa fa-caret-right"></i> Online Checkout Options</h3><br>
        </div>
    </div>

    <div class="title_content_top">
        <p>Checkout is the final action i.e. payout by the customer for the purchases done at a Webstore. A payment gateway is a software program integrated to your website to transmit transaction data to the Credit Card/Net Banking/Cash Card/Mobile Payment acquirer for authorization and settlement. Here you can configure online checkout options to your store after tie-up with respective payment gateway.</p>
    </div>
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="mmctrl_box mrgin_gap0">
                <div class="mmcaption">Selected Checkout Options</div>
                <p class="mrgin_gap20">These Checkout options are currently configured to your store. To modify the configuration, click 'Edit.' </p>
                <div class="checkoutholder">

                    <table class="table table-striped responsive-utilities jambo_table bulk_action" id="tblUsers">
                        <thead>
                            <tr class="">
                                @*<th>
                                    <div class="squaredThree">
                                        <input type="checkbox" value="None" id="check-all" name="check" />
                                        <label for="check-all"></label>
                                    </div>
                                </th>*@
                                <th class="column-title" style="display: table-cell;">Id </th>
                                <th class="column-title" style="display: table-cell;">Payment Gatway</th>
                                <th class="column-title" style="display: table-cell;">Merchant Key</th>
                                <th class="column-title" style="display: table-cell;">Currencie</th>
                                <th class="column-title" style="display: table-cell;">Created On</th>
                                <th class="column-title" style="display: table-cell;">Edit</th>
                            </tr>
                        </thead>


                        @if (Model.Count() != 0)
                        {
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="" id="@item.Payment_GateWay_ID">
                                        <td>@item.Payment_GateWay_ID</td>
                                        <td>@item.Payment_Gateway</td>
                                        <td>@item.Merchant_Key</td>
                                        <td>@item.Currency_Type</td>
                                        <td>@item.Created_On</td>
                                        <td>
                                        <a href="@Url.Action("Payment", "Settings", new { id = item.Payment_GateWay_ID })" title=" view">Edit</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        }
                        else
                        {
                            <div class="alert alertnew alert-info fade in">
                                <a href="#" class="close" data-dismiss="alert">×</a>
                                <strong>Warning!</strong> Payment Gateway List Not Found
                            </div>
                        }
                    </table>



                    @*<ul class="checkoutholder">
                        <li>
                            <img src="images/Payment/Hsbc.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h2><a href="Settings_Checkoutoptions_Gateway_edit.html">Edit</a></h2>
                                    <h3><a href="Settings_Checkoutoptions_Gateway_edit.html">Remove</a></h3>
                                    <div class="clearfix"></div>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Paypal.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h2><a href="Settings_Checkoutoptions_Gateway_edit.html">Edit</a></h2>
                                    <h3><a href="Settings_Checkoutoptions_Gateway_edit.html">Remove</a></h3>
                                    <div class="clearfix"></div>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Yesbank.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h2><a href="Settings_Checkoutoptions_Gateway_edit.html">Edit</a></h2>
                                    <h3><a href="Settings_Checkoutoptions_Gateway_edit.html">Remove</a></h3>
                                    <div class="clearfix"></div>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>
                    </ul>*@
                </div>
            </div>
            <br>

            @*<div class="mmctrl_box mrgin_gap0">
                <div class="mmcaption">Available Checkout options</div>
                <p class="mrgin_gap20">To add the checkout options to your store, after a tie-up with the respective Payment Gateway (PG) Service provider, click on the relevant checkout option and enter the necessary details as informed by the PG Service Provider. </p>

                <div class="checkoutholder">
                    <ul class="checkoutholder">
                        <li>
                            <img src="images/Payment/Sbi.png" class="img-responsive" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Axis.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Bankofamerica.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Citibank.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Icici.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Mastercard.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img src="images/Payment/Paytm.png" alt="">
                            <div class="checkout-captionholder">
                                <div class="caption_blur"></div>
                                <div class="captiontext">
                                    <h1><a href="Settings_Checkoutoptions_GatewayConfiguration.html">ADD</a></h1>
                                    <p>Whatever It Is - Always Awesome</p>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>*@
        </div>
        <div class="clearfix"></div>
        <div class="col-md-12 col-sm-6 col-xs-12 graycolorbg">
            <div class="pull-right">
                <a href="@Url.Action("Payment", "Settings")" title="Add"> <button type="submit" class="btn btn-default dtn-save" name="Command" value="Save&amp;List">Add New Payment Gateway</button></a>
            </div>
        </div>
    </div>
    <!-- /page content -->
    <br>