Admin/Gizmobaba/Controllers/CategoryManageController.cs
using Gizmobaba.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gizmobaba.Service.Interfaces;
using Gizmobaba.Utility;
using AutoMapper;
using System.IO;


namespace Gizmobaba.Controllers
{
    [Authorize]
    public class CategoryManageController : BaseController<CategoryManageController>
    {
        private readonly ICategoryService _categoryService;
        // GET: CategoryManage

        public CategoryManageController(ICategoryService _categoryService) {
            this._categoryService = _categoryService;
        }

        public ActionResult Index()
        {
            try
            {
                //Mapper.CreateMap<CategoryDto, Category>();
                IEnumerable<CategoryDto> cateList = _categoryService.GetCategories();
                //IEnumerable<Category> cateLists = Mapper.Map<List<Category>>(cateList);
                 IList<Category> cateViewLists = new List<Category>();
                foreach (CategoryDto data in cateList)
                {
                    Category categoryVIew = new Category
                    {
                        CATEGORY_ID = data.CATEGORY_ID,
                        CATEGORY_DESC = data.CATEGORY_DESC,
                        CREATEDF_ON = data.CREATEDF_ON,
                        ICON = data.ICON,
                        SEQ_NO = data.SEQ_NO,
                        ProductCount = data.ProductsCount,
                        REFERENCE_CODE = data.REFERENCE_CODE,
                        SubCategories = data.SubCategory.Where(a=>a.CATEGORY_ID == data.CATEGORY_ID).Select(s => new SubCategoriesViewModel
                        {
                            REFERENCE_CODE = s.REFERENCE_CODE,
                            SUB_CAT_DESC = s.SUB_CAT_DESC,
                            CATEGORY_ID = s.CATEGORY_ID,
                            DESCRIPTION = s.DESCRIPTION,
                            NUMBER_OF_COLUMNS = s.NUMBER_OF_COLUMNS,
                            SUB_CAT_GROUP = s.SUB_CAT_GROUP,
                            RANK = s.RANK,
                            SUB_CAT_ID = s.SUB_CAT_ID
                        }).ToList()
                    };

                    foreach (SubCategoriesViewModel subCategoryModel in categoryVIew.SubCategories)
                    {
                        subCategoryModel.ProductCount = _categoryService.GetProductCountbySubCatId(subCategoryModel.SUB_CAT_ID);
                    }
                    cateViewLists.Add(categoryVIew);
                    //SubCategoriesViewModel subCategories = new SubCategoriesViewModel();
                    //foreach (M_GB_SUB_CATEGORY subCategoryModel in data.SubCategory)
                    //{
                    //    subCategories.REFERENCE_CODE = subCategoryModel.REFERENCE_CODE;
                    //    subCategories.SUB_CAT_DESC = subCategoryModel.SUB_CAT_DESC;
                    //    subCategories.CATEGORY_ID = subCategoryModel.CATEGORY_ID;
                    //    subCategories.DESCRIPTION = subCategoryModel.DESCRIPTION;
                    //    subCategories.NUMBER_OF_COLUMNS = subCategoryModel.NUMBER_OF_COLUMNS;
                    //    subCategories.SUB_CAT_GROUP = subCategoryModel.SUB_CAT_GROUP;
                    //    subCategories.RANK = subCategoryModel.RANK;
                    //    subCategories.SUB_CAT_ID = subCategoryModel.SUB_CAT_ID;
                    //    categoryVIew.SubCategories.Add(subCategories);
                    //}
                }
                IEnumerable<Category> cateLists = cateViewLists;
                CategoryViewModel category = new CategoryViewModel();
                category.REFERENCE_CODE = "GBC0" + (cateList.LastOrDefault().CATEGORY_ID + 1);
                category.CategoryContentInformation = new CategoryContentInformation();
                category.CategorySeoInformation = new CategorySeoInformation();
                CategoryList model = new CategoryList
                {
                    categoryList = cateLists,
                    categoryViewModel = category
                };
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryManage/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult EditCategory(int id)
        {
            //CategoryDto category = _categoryService.GetCategory(id);
            //CategoryViewModel cvm = new CategoryViewModel
            //{
            //    CATEGORY_ID = category.CATEGORY_ID,
            //    CATEGORY_DESC = category.CATEGORY_DESC,
            //    CREATEDF_ON = category.CREATEDF_ON,
            //    ICON = category.ICON,
            //    SEQ_NO = category.SEQ_NO,
            //    REFERENCE_CODE = category.REFERENCE_CODE,
            //    CATEGORY_RANK = category.CATEGORY_RANK,
            //};

            Mapper.CreateMap<CategoryDto, CategoryViewModel>();
            CategoryDto category = _categoryService.GetCategory(id);
            //CategoryViewModel cvm = Mapper.Map<CategoryViewModel>(category);
            CategoryViewModel cvm = new CategoryViewModel
            {
                CATEGORY_ID = category.CATEGORY_ID,
                CATEGORY_DESC = category.CATEGORY_DESC,
                CATEGORY_RANK = category.CATEGORY_RANK,
                CREATEDF_ON = category.CREATEDF_ON,
                REFERENCE_CODE = category.REFERENCE_CODE,
                STATUS = category.STATUS,
                UPDATED_ON = category.UPDATED_ON,
                ICON = category.ICON
            };

            if (category.CategoryContentInformation != null)
            {
                CategoryContentInformation categoryContentInformation = new CategoryContentInformation
                {
                    TITLE = category.CategoryContentInformation.TITLE,
                    BODY = category.CategoryContentInformation.BODY,
                    IMAGE_URL = category.CategoryContentInformation.IMAGE_URL
                };
                cvm.CategoryContentInformation = categoryContentInformation;
            }
            if (category.CategorySeoInformation != null)
                {
                    CategorySeoInformation categorySeoInformation = new CategorySeoInformation
                    {
                        META_KEYWORD = category.CategorySeoInformation.META_KEYWORD,
                        META_DESC = category.CategorySeoInformation.META_DESC,
                        META_REFERENCE_CODE = category.CategorySeoInformation.META_REFERENCE_CODE,
                    };
                    cvm.CategorySeoInformation = categorySeoInformation;
                }

            return PartialView("~/Views/Shared/CategoryPartial.cshtml", cvm);
        }

        // POST: CategoryManage/Create
        [HttpPost]
        public ActionResult Create(CategoryViewModel categoryViewModel)
        {
            try
            {
                CATEGORY_CONTENT_INFORMATION categoryContentInformation = new CATEGORY_CONTENT_INFORMATION
                {
                    TITLE = categoryViewModel.CategoryContentInformation.TITLE,
                    BODY = categoryViewModel.CategoryContentInformation.BODY,
                    CREATEDF_ON = DateTime.Now
                };
                CATEGORY_SEO_INFORMATION categorySeoInformation = new CATEGORY_SEO_INFORMATION
                {
                    META_KEYWORD = categoryViewModel.CategorySeoInformation.META_KEYWORD,
                    META_DESC = categoryViewModel.CategorySeoInformation.META_DESC,
                    META_REFERENCE_CODE = categoryViewModel.CategorySeoInformation.META_REFERENCE_CODE,
                    CREATED_ON = DateTime.Now
                };
                CategoryDto category = new CategoryDto
                {
                    CATEGORY_DESC = categoryViewModel.CATEGORY_DESC,
                    CATEGORY_RANK = categoryViewModel.CATEGORY_RANK,
                    REFERENCE_CODE = categoryViewModel.REFERENCE_CODE,
                    CategoryContentInformation = categoryContentInformation,
                    CategorySeoInformation = categorySeoInformation,
                    CATEGORY_ID = categoryViewModel.CATEGORY_ID,
                    CREATEDF_ON = DateTime.Now
                };
                if (categoryViewModel.Image != null && categoryViewModel.Image.ContentLength > 0)
                {
                    var extension = Path.GetExtension(categoryViewModel.Image.FileName);
                    if (extension != null)
                    {
                        string imagetype = extension.ToLower();
                        var rondom = Guid.NewGuid() + imagetype;
                        var path = Path.Combine(ConfigurationManager.AppSettings["CatimageUrl"] + "\\" + rondom);
                        if (imagetype == ".jpg" || imagetype == ".png" || imagetype == ".gif" || imagetype == ".jpeg")
                        {
                            categoryViewModel.Image.SaveAs(path);
                            category.CategoryContentInformation.IMAGE_URL = rondom;
                        }
                    }
                }
                _categoryService.Create(category);
                if (category.CATEGORY_ID == 0)
                    TempData["SuccessMessage"] = "Category successfully added.";
                else
                    TempData["SuccessMessage"] = "Category successfully updated.";
            }
            catch (Exception exception)
            {
                TempData["ErrorMessage"] = exception.Message;
            }
            return RedirectToAction("Index");

        }

        // POST: CategoryManage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CategoryDto category)
        {
            try
            {
                _categoryService.UpdateCategory(category);

Admin/Gizmobaba/Views/CategoryManage/Create.cshtml
@model Gizmobaba.Models.Category
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="page-title">
            <div class="title_left">
                <h3>Add Category</h3><br>
            </div>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.CATEGORY_DESC, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.TextBoxFor(model => model.CATEGORY_DESC, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CATEGORY_DESC, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ICON, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.ICON, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ICON, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

Admin/Gizmobaba/Views/CategoryManage/Index.cshtml
@model Gizmobaba.Models.CategoryList

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}
<link href="~/GizmobabaFiles/css/custom.css" rel="stylesheet" />
<script type="text/javascript">
    $(document).ready(function () {
        $("#catg_fun_showhide_ctrldiv").click(function () {
            $(".catg_fun_showhide_ctrl_dis").slideToggle("slow");
        });

        //$("#catg_navshow").click(function () {
        //    $("#childnav").slideToggle("slow");
        //});
        var dis;
        $(".catInsubcat").click(function () {
            $('.' + this.id).slideToggle("slow");
            dis = $(this);
            setTimeout(function () {
                if ($(dis).next().find('ul').css('display') != "none")
                    $(dis).find('i.fa-caret-right').addClass('fa-caret-down').removeClass('fa-caret-right');
                else
                    $(dis).find('i.fa-caret-down').addClass('fa-caret-right').removeClass('fa-caret-down');
            }, 1000);
        });
        $("#childnav").click(function () {
            $(".subcat").slideToggle("slow");
        });
    });
    function DeleteSubCategory(id) {
        var result = confirm("Want to delete?");
        if (result) {
            $.ajax({
                url: URL + '/CategoryManage/DeleteSubCategory/' + id,
                type: "Post",
                contentType: 'application/json; charset=utf-8',
                async: false,
                dataType: "json",
                success: function (data) {
                    $('li[id=' + id + ']').remove();
                },
                error: function (xhr) {
                    alert(xhr);
                }
            });
        }
    }
</script>
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>Manage Product Categories</h3><br>
        </div>
    </div>

    <div class="title_content_top">
        <p>Category Management is taxonomy of arranging products in a hierarchy. The ‘Category Management’ module has been completely revamped to a tree-structured (hierarchical) user interface (UI) to provide superior look & feel, quick loading and easy navigation. Now it’s much easier to create and manage the Categories, Sub-categories and attributes. You can directly edit the name of a ‘Category’ or ‘Ref. code’ by just double clicking the respective values and also find the product count against respective categories. A search box also provided for finding required Categories/Sub-Categories quickly.</p>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-12 col-sm-12 col-xs-12"><a data-toggle="modal" href="#normaladd" class="btn btn-default btn-sm pull-right"> <i class="fa fa-plus"></i> Add new Root Category</a></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title" id="divcategory">
                    <h2>Attribute for Product Categories</h2>
                    <div class="clearfix"></div>
                </div>

                @if (TempData["SuccessMessage"] != null && TempData["SuccessMessage"] != "")
                {
                    <div class="alert alertnew alert-success fade in">
                        <a href="#" class="close" data-dismiss="alert">×</a>
                        <strong>Success!</strong> @TempData["SuccessMessage"]
                    </div>
                }
                @if (TempData["ErrorMessage"] != null && TempData["ErrorMessage"] != "")
                {
                    <div class="alert alertnew alert-danger fade in">
                        <a href="#" class="close" data-dismiss="alert">×</a>
                        <strong>Error!</strong> @TempData["ErrorMessage"]
                    </div>
                }
                <div class="x_content">
                    <div class="catg_adddsply catg_adddsply_bdr">
                        <ul class="catg_adddsply" id="ulCat">
                            <li>
                                <div class="catg-name_cptn" >
                                    <h1>Category</h1>
                                    <h2>
                                        <div class="pull-right">
                                            @*<form class="" role="search">*@
                                            <div class="input-group">
                                                <input type="text" class="form-control" placeholder="Search" name="q" id="txtCategorySearch">
                                                <div class="input-group-btn">
                                                    <button class="btn btn-default btnsrchgap" id="btnSearch" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                                </div>
                                            </div>
                                            @*</form>*@
                                        </div>
                                    </h2>
                                </div>
                                <div class="catg-refcode_cptn">Ref. Code</div>
                                <div class="catg-pcount_cptn">Product Count</div>
                                <div class="catg-action_cptn">Actions</div>
                            </li>
                            @foreach (var item in Model.categoryList)
                            {
                                <li id="@item.CATEGORY_ID" class="catInsubcat">
                                    <div class="catg-name" id="catg_navshow" style="cursor: pointer;"><i class="fa fa-caret-right"></i> @item.CATEGORY_DESC</div>
                                    <div class="catg-refcode">@item.REFERENCE_CODE</div>
                                    <div class="catg-pcount"> @item.ProductCount</div>
                                    <div class="catg-action">
                                        <a href="@Url.Action("SubCategories", "CategoryManage", new {id = item.CATEGORY_ID})" title="Add"><i class="fa fa-plus"></i></a>
                                        <a href="javascript:;" onclick="$(this).next().click();"><i class='fa fa-pencil-square-o'></i></a>
                                        @Ajax.ActionLink("Edit", "EditCategory", new { id = item.CATEGORY_ID }, new AjaxOptions() { OnSuccess = "EditCategoryCallBack", UpdateTargetId = "AddEditPartialViewLoad" }, new { @class = "hide" })
                                        <a href="@Url.Action("SubCategories", "CategoryManage", new {id = item.CATEGORY_ID})" title="Attribute"><i class="fa fa-list"></i></a>
                                        <a data-toggle="modal" href="#normaldelete" onclick="deleteCategory(@item.CATEGORY_ID)" title="Delete"><i class="fa fa-trash-o"></i></a>
                                    </div>
                                </li>
                                foreach (var list in item.SubCategories)
                                {
                                    <li class="catg_subname_holder" id="@list.SUB_CAT_ID">
                                        <ul class="catg_adddsply subcat @item.CATEGORY_ID" style="display: none;">
                                            <li>
                                                <div class="catg-name">
                                                    <i class="fa fa-caret-right"></i> @list.SUB_CAT_DESC
                                                </div>
                                                <div class="catg-refcode">@list.REFERENCE_CODE</div>
                                                <div class="catg-pcount"> @list.ProductCount</div>
                                                <div class="catg-action">
                                                    @*<a href="@Url.Action("Edit", "EditCategory", new {id = item.CATEGORY_ID})" title="Add"><i class="fa fa-plus"></i></a>*@
                                                    <a href="@Url.Action("EditCatSubCategory", "CategoryManage", new { id = list.CATEGORY_ID, subCatID=list.SUB_CAT_ID })"><i class='fa fa-pencil-square-o'></i></a>
                                                    @*@Ajax.ActionLink("Edit", "EditCategory", new {id = item.CATEGORY_ID}, new AjaxOptions() {OnSuccess = "EditCategoryCallBack", UpdateTargetId = "AddEditPartialViewLoad"}, new {@class = "hide"})*@
                                                    @*<a href="@Url.Action("SubCategories", "CategoryManage", new {id = item.CATEGORY_ID})" title="Attribute"><i class="fa fa-list"></i></a>*@
                                                    <a data-toggle="modal" href="javascript:;" onclick="DeleteSubCategory(@list.SUB_CAT_ID)" title="Delete"><i class="fa fa-trash-o"></i></a>
                                                    @*<a data-toggle="modal" href="#normaldelete" title="Delete"><i class="fa fa-trash-o"></i></a>*@
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                }
                            }

                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<div id="AddEditPartialViewLoad">
    @{
        Html.RenderPartial("~/Views/Shared/CategoryPartial.cshtml", Model.categoryViewModel);
    }
</div>



<div id="normaldelete" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body dfltpad">
                @*<p style="padding:20px;">By deleting a category, it's associated product(s) also will be deleted. Are you sure to delete the category 'Shop Shop Shop....'?</p>*@
                <p style="padding:20px;">By deleting a category, it's associated product(s) also will be deleted. Are you sure to delete the category ?</p>
            </div>
            <div class="modal-footer">
                <input type="hidden" id="deleteCategoryId" />
                <a class="btn btn-default categoryDeleteLink" onclick="CategoryDeleteMethod('categoryId')" id="categoryId">Ok</a>
                <button type="button" class="btn btn-default dismissModal" data-dismiss="modal" aria-hidden="true">Cancel</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/category.js"></script>
<script>
    NProgress.done();
    $(document).ready(function () {
        $('body').on('click', 'button[type="submit"]', function () {
            var emptyVal = 0;
            $('[required]').each(function () {
                if ($(this).val() == "") {
                    emptyVal = 1;
                }
            });
            if (emptyVal != 1)
                $('.loader-container').removeClass('hide');
        });
    });
    function validateForm() {
    }
</script>
<div class='loader-container hide'>
    <div class='loader'>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--text'></div>
    </div>
</div>
<link href="~/Content/loader.css" rel="stylesheet" />
<script src="~/Scripts/common.js"></script>