Admin/Gizmobaba/Controllers/MarketController.cs
using AutoMapper;
using Gizmobaba.Models;
using Gizmobaba.Service.Interfaces;
using Gizmobaba.Utility;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Gizmobaba.Controllers
{
    public class MarketController : Controller
    {
        private readonly IDiscountService _discountService;
        // GET: CategoryManage

        public MarketController(IDiscountService discountService)
         {
             this._discountService = discountService;
         }

        // GET: Market/Create
        public ActionResult Create(int id=0)
        {
            DiscountModel model = new DiscountModel();
            try
            {
                if(id != 0)
                {
                    Mapper.CreateMap<M_GB_USER_DISCOUNT, DiscountModel>();
                    M_GB_USER_DISCOUNT discount = _discountService.GetDiscountVoucher(id);
                    model = Mapper.Map<DiscountModel>(discount);
                }
            }
            catch (Exception exception)
            {

            }
            return View(model);
        }

        // POST: Market/Create
        [HttpPost]
        public ActionResult Create(M_GB_USER_DISCOUNT userDiscount)
        {
           // DiscountModel Model = new DiscountModel();
            try
            {
                // TODO: Add insert logic here
                if (userDiscount != null)
                {
                    userDiscount.CREATED_ON = DateTime.Now;
                    if (_discountService != null) _discountService.AddUsersDiscount(userDiscount);
                    //if(userDiscount.DISCOUNT_ID == 0)
                    //    TempData["Message"] = " Discount voucher successfully added";
                    //else
                    //    TempData["Message"] = " Discount voucher successfully updated";

                    //Mapper.CreateMap<DiscountModel, M_GB_USER_DISCOUNT>();
                    //Model = Mapper.Map<DiscountModel>(userDiscount);
                }
            }
            catch (Exception exception)
            {
                TempData["Error"] = exception.Message;
            }
            return RedirectToAction("DiscountVouchers");
            //return View(Model);

        }
        // POST: Market/Delete/5
        [AllowAnonymous]
        [HttpPost]
        public JsonResult Delete(int id)
        {
            try
            {
                if (id == 0)
                    return Json(CustomStatus.ErrorCodeToString(CustomStatus.ProductMessageStatus.Empty),
                        JsonRequestBehavior.DenyGet);
                else
                {
                    _discountService.DeleteDiscount(id);
                    //return RedirectToAction("CreateOrder");
                    return Json(CustomStatus.ErrorCodeToString(CustomStatus.ProductMessageStatus.Success),
                        JsonRequestBehavior.DenyGet);
                }
            }
            catch (Exception)
            {
                return Json(CustomStatus.ErrorCodeToString(CustomStatus.ProductMessageStatus.Failed), JsonRequestBehavior.DenyGet);
            }

        }
        [HttpGet]
        public ActionResult DiscountVouchers()
        {
            Mapper.CreateMap<M_GB_USER_DISCOUNT, DiscountModel>();
            IEnumerable<M_GB_USER_DISCOUNT> disList = _discountService.GetUsersDiscounts();
            IEnumerable<DiscountModel> dicountList = Mapper.Map<List<DiscountModel>>(disList);
            return View(dicountList);
        }
        public ActionResult DiscountVouchersSearch(string title, DateTime? fromDate, DateTime? toDate, string voucher)
        {
            Mapper.CreateMap<M_GB_USER_DISCOUNT, DiscountModel>();
            IEnumerable<M_GB_USER_DISCOUNT> disList = _discountService.DiscountVouchersSearch(title,fromDate,toDate,voucher);
            IEnumerable<DiscountModel> dicountList = Mapper.Map<List<DiscountModel>>(disList);
            return PartialView("DiscountVouchersPartial", dicountList);
        }
    }
}

Admin/Gizmobaba/Views/Market/Create.cshtml
@model Gizmobaba.Models.DiscountModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}


<div class="page-title">
    <div class="title_left">
        <h3>Manage Discount Vouchers</h3><br>
    </div>
</div>

<div class="title_content_top">
    <p>Unique Discount Vouchers (i.e. Voucher Codes) for different type of users can be created against the selected ‘Discount Voucher campaign’ here. ‘Discount Vouchers’ can be used only once, and the leftover balance amount (if any) cannot be reused. You can create Voucher codes by yourself or you can allow the auto generation of these codes. The number of voucher codes must be equal to number of ‘Registered’ users. You can also define ‘number of uses per user’ and ‘number of uses per voucher’ to control the usage.</p>
</div>
<div class="clearfix"></div>

<div class="row">
    <div class="clearfix"></div>
    <br />
    @if (TempData["Message"] != null && TempData["Message"] != "")
    {
        <div class="alert alertnew alert-success fade in">
            <a href="#" class="close" data-dismiss="alert">×</a>
            <strong>Success!</strong> @TempData["Message"]
        </div>
    }
    else if (TempData["Error"] != null && TempData["Error"] != "")
    {
        <div class="alert alertnew alert-danger fade in">
            <a href="#" class="close" data-dismiss="alert">×</a>
            <strong>Error!</strong> @TempData["Error"]
        </div>
    }
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="mmctrl_box mrgin_gap0 mmctrl_tble">
            <div class="mmcaption">Create Discount Voucher for Users</div>
            @using (Html.BeginForm("Create", "Market", FormMethod.Post, new { enctype = "multipart/form-data", onSubmit = "return validateForm();" }))
            {
                <div class="form-group">
                    <br/>
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Select user Type <span class="red">*</span></label>
                        <div class="col-md-7">
                            <select class="select2_single form-control" tabindex="-1" name="USER_GROUP_ID">
                                <option selected="selected" value="6"> All </option>
                                <option value="10">Silver User</option>
                                <option value="11">Gold User</option>
                                <option value="12">Platinum Users</option>
                            </select>
                            @Html.HiddenFor(model => model.DISCOUNT_ID)
                        </div>

                    </div>
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Campaign Title <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.CAMPAIGN_TITLE, new {@class = "form-control", required = ""})
                        </div>

                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Voucher Code <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.VOUCHER_CODE, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                            <small>To enter multiple codes use comma (ex. XHFSDD79,FKIE9DF9)</small>
                            @*<label>
                                    <input type="checkbox"> Let Martjack Create Voucher Code for me
                                </label>*@
                        </div>

                    </div>
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Discount <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.DISCOUNT, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                            <small>Note : %</small>
                        </div>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Voucher Date <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.VOUCHER_DATE, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                        </div>
                    </div>
                    <div class="col-md-5">
                        <label class="control-label col-md-5">Voucher Expiry Date <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.VOUCHER_EXPIRY_DATE, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                        </div>
                    </div>
                </div>
                <hr>
                <div class="form-group">

                    <div class="col-md-5">
                        <label class="control-label col-md-5">Number of uses per User <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.NUMBEROFUSERS, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                            <small>Note : Enter -1 for unlimited times</small>
                        </div>
                    </div>

                    <div class="col-md-5">
                        <label class="control-label col-md-5">Number of uses per Voucher <span class="red">*</span></label>
                        <div class="col-md-7">
                            @Html.TextBoxFor(model => model.NUMBEROFVOUCHER, new { @class = "form-control", required = "" })
                            @*<input id="" name="" placeholder="" required="" class="form-control" type="text">*@
                            <small>Note : Enter -1 for unlimited times</small>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="form-group">

                    <div class="col-md-5">
                        <label class="control-label col-md-5">Remarks </label>
                        <div class="col-md-7">
                            @Html.TextAreaFor(model => model.REMARKS, new { @class = "form-control", row="3" })
                            @*<textarea class="form-control" rows="3"></textarea>*@
                            <small>(Max. Characters 350)</small>
                        </div>
                    </div>

                </div>

                <div class="clearfix"></div>
                <br>
                <div class="col-md-12 col-sm-6 col-xs-12 graycolorbg">
                    <button type="button" id="btnBack" class="btn btn-dark pull-right">Cancel</button>
                    <button type="submit" class="btn btn-dark pull-right">Save and Return to Discount List</button>
                </div>
            }
        </div>
    </div>



</div>
<!-- /page content -->
<br>
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script>
    NProgress.done();
    $(document).ready(function () {
        $('#VOUCHER_DATE, #VOUCHER_EXPIRY_DATE').datepicker();
        $('#btnBack').click(function () {
            history.back();
        });
        $('button[type="submit"]').click(function () {
            var emptyVal = 0;
            $('[required]').each(function () {
                if ($(this).val() == "") {
                    emptyVal = 1;
                }
            });
            if (emptyVal != 1)
                $('.loader-container').removeClass('hide');
        });
    });
</script>
<div class='loader-container hide'>
    <div class='loader'>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--dot'></div>
        <div class='loader--text'></div>
    </div>
</div>
<link href="~/Content/loader.css" rel="stylesheet" />

<script src="~/Scripts/common.js"></script>

Admin/Gizmobaba/Views/Market/DiscountVouchers.cshtml
@model IEnumerable<Gizmobaba.Models.DiscountModel>

@{
    ViewBag.Title = "DiscountVouchers";
    Layout = "~/Views/Shared/_LayoutGizmobaba.cshtml";
}
    <div class="page-title">
        <div class="title_left">
            <h3>Discount Voucher Campaigns </h3><br>
        </div>
    </div>

    <div class="title_content_top">
        <p>A 'Discount Voucher' is a coupon containing specific 'code', which can be exchanged for a financial discount during checkout. You need to run ‘Discount Voucher Campaigns’ for creating these ‘Discount Vouchers’. This interface allows you to create, edit or delete ‘Discount Voucher Campaigns’. You can also manage ‘Discount Vouchers’ of the required Campaign through the respective ‘Create’ link. Facility has been provided for sorting these campaigns through multiple options.</p>
    </div>
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="mmctrl_box mrgin_gap0 mmctrl_tble">
                <div class="mmcaption">Search</div>


                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#SearchbyCampaigns" id="btnSearchbyCampaigns" aria-controls="home" role="tab" data-toggle="tab">Search by Campaigns Title</a></li>
                    <li role="presentation"><a href="#SearchbyVoucher" aria-controls="profile" role="tab" data-toggle="tab">Search by Voucher Code</a></li>
                </ul>

                <!-- Tab panes -->
                <div style="display: none;" id="searchslidehs-panel">
                    <div class="tab-content">
@using (Ajax.BeginForm("DiscountVouchersSearch", "Market", new { },
                                        new AjaxOptions
                                        {
                                            HttpMethod = "POST",
                                            InsertionMode = InsertionMode.Replace,
                                            UpdateTargetId = "partialView"
                                        }, new { id = "getOrderDate" }))
                                                                        {
                        <div role="tabpanel" class="tab-pane active" id="SearchbyCampaigns">
                            <div class="mrgin_gap20">
                            
                                    <br>

                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label col-md-5" for="">Campaign Title </label>
                                            <div class="col-md-7">
                                                <input id="" name="title" placeholder="" class="form-control" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label class="control-label col-md-5">Discount Type</label>
                                                <div class="col-md-7">
                                                    <select class="select2_single form-control" tabindex="-1">
                                                        <option selected="selected" value=""> -- Select -- </option>
                                                        <option value="">Regular</option>
                                                        <option value="">EMI</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="form-group">
                                        <div class="col-md-5">
                                            <label class="control-label col-md-5" for="">Discount From</label>
                                            <div class="col-md-7">
                                                <input id="disfromDate" name="fromDate" placeholder="" class="form-control" type="text">
                                                <small>from</small>
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label class="control-label col-md-5">Discount To</label>
                                                <div class="col-md-7">
                                                    <input id="distoDate" name="toDate" placeholder="" class="form-control" type="text">
                                                    <small>to</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @*</form>*@
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane active" id="SearchbyVoucher">
                            <div class="mrgin_gap20">
                                @*<form id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left">*@
                                    <br>
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <label class="control-label col-md-2" for="">Voucher Code </label>
                                            <div class="col-md-9">
                                                <input id="" name="voucher" placeholder="" class="form-control" type="text">
                                            </div>
                                        </div>
                                    </div>
                                <br />

                                @*</form>*@
                            </div>
                        </div>
    <div class="col-md-12 col-sm-6 col-xs-12 graycolorbg">
        <button type="submit" class="btn btn-dark pull-right">Search</button>
    </div>
                                                                        }
                    </div>
                   
                    </div>
                </div>

                <div class="sreachbtnhs-slide">
                    <a href="#" class="sreachbtnhs_btn-slide">Search Here</a>
                </div>
            </div>

        <div class="clearfix"></div>
        <br>
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="mmctrl_box mrgin_gap0 mmctrl_tble">
                <div class="mmcaption">Available Voucher Campaigns</div>
                <div id="partialView">

                    @{
                        Html.RenderPartial("~/Views/Shared/DiscountVouchersPartial.cshtml", Model);
                    }
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
    <br>
<div class="col-md-12 col-sm-6 col-xs-12 graycolorbg">
    <a href="@Url.Action("create", "Market")"><button type="button" class="btn btn-dark pull-right">Create Discount Voucher</button></a>
</div>

<br />
<hr />
<script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    var URL = "http://www.pakkadial.com/Admin/";
        NProgress.done();
        $(document).ready(function () {
            $('#disfromDate,#distoDate,#fromDate,#toDate').datepicker();

            $(".sreachbtnhs-slide").click(function () {
                $("#searchslidehs-panel").slideToggle("slow");
                $(this).toggleClass("active"); return false;
            });

            $(".sreachbtnhs-slide").click(function () {
                $("#searchslidehs-panel2").slideToggle("slow");
                $(this).toggleClass("active"); return false;
            });
        }); 
        function DeleteDis(id)
        {
            if(confirm("Are you sure you want to delete this?")){
                $.ajax({
                    url: URL + '/Market/Delete/'+id,
                    //url: '/Market/Delete/'+ id,
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    async: false,
                    dataType: "json",
                    success: function (data) {
                        alert('Discount voucher deleted');
                        $('#'+id).remove();
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }
                });
            }
            else{
                return false;
            }
        }
</script>